### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by rolero** [pchab/ProjectRTC#20]
When I try to start the project I get the following error:

npm ERR! weird error 127
npm WARN This failure might be due the use of  legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.debian.
npm ERR! not ok code 0

**Comment by rolero** [comment]
I am able to start the server using: nodejs app.js but when I open to localhost:3000 I get the following error:

SyntaxError: Unexpected identifier in /home/rkillaars/peer3/ProjectRTC/views/index.ejs while compiling ejs
   at Object.Function (<anonymous>)
   at Object.Template.compile (/home/rkillaars/peer3/ProjectRTC/node_modules/ejs/lib/ejs.js:460:12)
   at Object.compile (/home/rkillaars/peer3/ProjectRTC/node_modules/ejs/lib/ejs.js:288:16)
   at handleCache (/home/rkillaars/peer3/ProjectRTC/node_modules/ejs/lib/ejs.js:147:16)
   at View.exports.renderFile [as engine] (/home/rkillaars/peer3/ProjectRTC/node_modules/ejs/lib/ejs.js:350:14)
   at View.render (/home/rkillaars/peer3/ProjectRTC/node_modules/express/lib/view.js:126:8)
   at tryRender (/home/rkillaars/peer3/ProjectRTC/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/home/rkillaars/peer3/ProjectRTC/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/home/rkillaars/peer3/ProjectRTC/node_modules/express/lib/response.js:961:7)
   at index (/home/rkillaars/peer3/ProjectRTC/app/routes.js:5:9)

**Comment by psellers89** [comment]
I had the same problem.
I fixed it by installing version 1.0 of ejs.
run : 
npm i ejs@1.0

**Comment by nateridderman** [comment]
I had a different stack trace but it was solved by the upgrading ejs. Thanks!

**Comment by zhangjh** [comment]
i had the same problem, and 'reinstall ejs@1.0' fixed
